### ISSUE TITLE
Conversion of teachable machine model to tflite

### ISSUE THREAD

**Issue by nikJ13** [AyushBherwani1998/flutter_teachable_ml#2]
Wanted to know how did you convert teachable machine learning model (generated from the website) into tflite?

**Comment by AyushBherwani1998** [comment]
Hey @nikJ13 in the website while you are exporting model, it will have different options, from which one is tflite model.

**Comment by nikJ13** [comment]
Yeah, a lot of online blogs have also said this. But, I just trained a model on that website. On clicking the "Export model" option, this is what it showed - 

![image](https://user-images.githubusercontent.com/51831161/100426486-f1922500-30b6-11eb-99fa-3916b7581fe4.png)

Didn't see any option of converting to tflite.

**Comment by AyushBherwani1998** [comment]
That's weird, I do see an option. Which project is this, image, audio, or pose?

**Comment by AyushBherwani1998** [comment]
![Screenshot 2020-11-27 at 1 51 09 PM](https://user-images.githubusercontent.com/34301187/100427153-091ddd80-30b8-11eb-98b5-2e5d2c5ffa88.png)

**Comment by nikJ13** [comment]
It's a pose project

**Comment by AyushBherwani1998** [comment]
Oh, it's same in my case too. I don't see an option when project is a pose project. I think it doesn't support export as tflite as a pose project.

**Comment by nikJ13** [comment]
Oh...shoot....kk
